### ISSUE TITLE
希望可以增加icon字段，能更好的显示标题ico

### ISSUE THREAD

**Issue by dongshull** [MetaCubeX/metacubexd#1022]
[icon](https://wiki.metacubex.one/config/proxy-groups/#icon)[¶](https://wiki.metacubex.one/config/proxy-groups/#icon)
在 api 返回icon所输入的字符串，以在该策略组显示 (需要使用 api 的前端适配)

**Comment by YetAnotherZephyruso** [comment]
请问你们的字符串一般是什么格式的？是icon的url还是什么

**Comment by dongshull** [comment]
> 请问你们的字符串一般是什么格式的？是icon的url还是什么

url，http的url图床

**Comment by junjiego2** [comment]
确实，目前proxy group标题只能添加emoji来增强显示，而且各个系统显示的emoji效果各不相同

**Comment by YetAnotherZephyruso** [comment]
现在应该好了

**Comment by junjiego2** [comment]
> 现在应该好了

用上了，效果很不错，只是感觉每次打开页面，icon要等一会才加载上，是没有本地缓存吗

**Comment by YetAnotherZephyruso** [comment]
> 没有本地缓存吗

缓存是浏览器本身的机制，不需要去刻意设定，图床尽量用国内的吧

**Comment by YetAnotherZephyruso** [comment]
emoji本身也支持，现在url图片也支持，爱用啥用啥吧
