### ISSUE TITLE
mac 上brew安装sing box, 打开127.0.0.1:9090 出现{"message":"Unauthorized"}

### ISSUE THREAD

**Issue by xioqing** [MetaCubeX/metacubexd#1034]
"experimental": {
    "cache_file": {
      "enabled": true
    },
    "clash_api": {
      "external_controller": "0.0.0.0:9090",
      "external_ui": "metacubexd",
      "external_ui_download_url": "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip",
      "external_ui_download_detour": "direct",
      "default_mode": "rule",
      "secret": "riztuj-meNgas-ceqqe9"
    }
  }

同样的配置在openwrt上没问题

**Comment by YetAnotherZephyruso** [comment]
singbox的默认web控制路径是http://127.0.0.1:9090/ui

**Comment by xioqing** [comment]
> singbox的默认web控制路径是http://127.0.0.1:9090/ui

谢谢告知, 可以打开了, 为什么我打开openwrt的不需要加/ui呢?
总之谢谢了.

**Comment by YetAnotherZephyruso** [comment]
> openwrt的不需要加/ui

不同软件在处理的时候的逻辑不一样，这个需要你问对应的sing-box开发和你在openwrt上用的软件的开发
