### ISSUE TITLE
建议 增加选项-隐藏不可用代理

### ISSUE THREAD

**Issue by kanao7** [MetaCubeX/metacubexd#1049]
代理组加了hidden参数，有时想手动切换节点，就要修改配置文件再很麻烦，我看到yacd面板有这个选项，如果xd能加上就很方便快捷了，感谢

**Comment by Lovefish** [comment]
一直都有啊

**Comment by kunish** [comment]
这个功能前端就不重复做了，跟后端冲突

如果前端也实现一个，两个功能的界限不明显，而且属于小众功能，暂不考虑实现
