### ISSUE TITLE
[FR] 恢复被删除的双行渲染

### ISSUE THREAD

**Issue by zutzo** [MetaCubeX/metacubexd#1064]
rt
PC 端 没有双行极其影响观感
望大佬加回去

**Comment by kunish** [comment]
在双行渲染的根本问题（展开一侧后另一侧空空如也，强迫症难受）没有被解决之前先不加，等再考虑考虑

**Comment by rammiah** [comment]
PC上好丑啊/(ㄒoㄒ)/~~

**Comment by kunish** [comment]
恢复了，先就这样吧

https://github.com/MetaCubeX/metacubexd/pull/1068

**Comment by kunish** [comment]
@zutzo got it，麻烦再提供一下屏幕尺寸和缩放大小

**Comment by junjiego2** [comment]
新版在手机端手动切换节点变麻烦了，以前一行能显示两列，现在要翻好久
![photo_2024-10-11_13-28-54](https://github.com/user-attachments/assets/98c5e755-e666-4e6a-a041-daa8598e194a)

**Comment by kunish** [comment]
> > @zutzo got it，麻烦再提供一下屏幕尺寸和缩放大小
> 
> 屏幕尺寸是 `6.67英寸 ` 缩放比例是 100%

OK
