### ISSUE TITLE
新版ui在移动端设备手动切换节点，效率变低了

### ISSUE THREAD

**Issue by junjiego2** [MetaCubeX/metacubexd#1071]
虽然已经有相似的issue #1064 且已经关闭，我希望开发者能在显示效果这方面再考虑优化一下，新版的ui在移动端手动切换节点比起v.1.152.0，效率有所降低。ui留白过大，利用率不高。附上新旧版对比图，移动设备是iPhone 15 pro。

屏幕参数：6.1 英寸（对角线），2556 x 1179 像素，460 ppi，缩放 100% 

![对比图](https://github.com/user-attachments/assets/5e6045ec-62c6-4d9a-a423-a612dbfff078)

**Comment by Lovefish** [comment]
你用的什么鸡场？

**Comment by junjiego2** [comment]
> 你用的什么鸡场？

瓦工，然后还有自建，以及白嫖cloudflare，然后用substore整合起来

**Comment by kunish** [comment]
考虑要不要发起一个 poll 统计一下，节点名的字数一般都有多少，我自用的节点名字数比较多，所以适配的时候虚空索敌了

要是字数基本上都在 10 个以内的话，那就还保持两列

**Comment by Lovefish** [comment]
> 考虑要不要发起一个 poll 统计一下，节点名的字数一般都有多少，我自用的节点名字数比较多，所以适配的时候虚空索敌了
> 
> 要是字数基本上都在 10 个以内的话，那就还保持两列

基本字数都挺少的。但问题是不管字数是否多于10，大部分用手机端看的都不会在意这个节点上面写什么，可能就看只看前几个字地区，或者图标的国旗。

所以我觉得给一个选项是比较好的，喜欢两排的就是自己设成两列，喜欢一排要字看得全一点的就一列

**Comment by junjiego2** [comment]
> 考虑要不要发起一个 poll 统计一下，节点名的字数一般都有多少，我自用的节点名字数比较多，所以适配的时候虚空索敌了
> 
> 
> 
> 要是字数基本上都在 10 个以内的话，那就还保持两列

有些机场的节点名字确实很长，包含节点倍率，落地 isp，运营商信息，我一般会用 substore 批量重命名一下

**Comment by kunish** [comment]
> > 考虑要不要发起一个 poll 统计一下，节点名的字数一般都有多少，我自用的节点名字数比较多，所以适配的时候虚空索敌了
> > 要是字数基本上都在 10 个以内的话，那就还保持两列
> 
> 有些机场的节点名字确实很长，包含节点倍率，落地 isp，运营商信息，我一般会用 substore 批量重命名一下

了解了，还是喜欢保持名字简洁，不需要太长的描述

**Comment by Lovefish** [comment]
> > > 考虑要不要发起一个 poll 统计一下，节点名的字数一般都有多少，我自用的节点名字数比较多，所以适配的时候虚空索敌了
> > > 要是字数基本上都在 10 个以内的话，那就还保持两列
> > 
> > 
> > 有些机场的节点名字确实很长，包含节点倍率，落地 isp，运营商信息，我一般会用 substore 批量重命名一下
> 
> 了解了，还是喜欢保持名字简洁，不需要太长的描述

而且我也发现长按节点的话，是会有一个pop up来显示完整的名称的，所以如果有缩略的话，其实是还好。甚至可以把节点显示成为dot可选，更简洁，有些人可能只是单纯要选择是绿色的，可用节点，如果要查看可以长按dot来显示说当前这个是什么。

**Comment by devioa** [comment]
同感，留白部分太大，看起来也不好看，已经滚回`1.151.0`版本用了，等改好再pull回来吧

**Comment by dream-hack** [comment]
其实不单单节点名字太长显示不全，更主要的是节点数量一多，浏览节点太痛苦呢。
暂时先回滚老版本。。。

**Comment by Rulio723** [comment]
确实，现在节点名字在电脑端已经显示不全了，就显示几个字，有点难受

**Comment by junjiego2** [comment]
> 可以改回原来那样吗，已经被丑晕了

可以自己替换旧版本然后不升级，还有请友好发言，作者的 ui 还是好看的，只不过在移动设备的显示逻辑不太理想。

**Comment by Lovefish** [comment]
改版的两行利用率还是太低。
第一行就单纯的是节点的标题，其他三个元素应该尽可能放在第二行吧。
还有可以增加一个模式完全缩略成dot，然后直接点dot来切换节点，我记得yacd是可以这样

**Comment by kunish** [comment]
![Uploading image.png…]()

或者这样

**Comment by junjiego2** [comment]
> <img width="402" alt="image" src="https://github.com/user-attachments/assets/ffb74f25-033c-404d-b454-4a040a4adb53">
> 
> 
> 
> 
> 
> 或者这样

这个应该就是旧版 1.152.0 那个显示逻辑吧，遇到信息多的，卡片会放大成 3 行显示![image](https://github.com/user-attachments/assets/faccac7f-6013-4ab9-9958-1c6ec601ddc0)

**Comment by kunish** [comment]
<img width="838" alt="image" src="https://github.com/user-attachments/assets/25cfac54-3e50-4b42-af11-c06054876939">

对啊，还可以更多

**Comment by junjiego2** [comment]
> <img width="838" alt="image" src="https://github.com/user-attachments/assets/25cfac54-3e50-4b42-af11-c06054876939">
> 
> 
> 
> 对啊，还可以更多

我觉得保留协议类型以及延迟的 highlight 就够了，不然看着就像笔记上用五颜六色的荧光笔标注的重点，全都是重点了

**Comment by kunish** [comment]
> @kunish 建议先把Twemoji移除了，这个东西全是bug，在一些浏览器里连文字都无法显示了

可以在设置里关掉

**Comment by kunish** [comment]
> > 可以在设置里关掉
> 
> 并不是设置开关那么简单的问题， 新用户一看连文字都不能显示，直接给人家劝退了 老用户每次新开都得先去设置里把开关关了才能正常用

那我改成默认不开了

**Comment by kunish** [comment]
<img width="562" alt="image" src="https://github.com/user-attachments/assets/333f9552-1cf1-44b7-b97a-a2644bdafa8a">

OK 的呀，移动端什么表现？

**Comment by junjiego2** [comment]
> @kunish 
> 
> 中文是宋体不是雅黑，颜色组合也很奇怪，其实也可以把这些奇奇怪怪的主题都删掉，只留一套精心设计的明暗主题就行
> 
> 
> 
> ![673e054f8abb4d6372de1f30f2e4940f.jpeg](https://ice.frostsky.com/2024/10/11/673e054f8abb4d6372de1f30f2e4940f.jpeg)

winter/sunset 作为明暗主题就挺棒的

**Comment by toddyoe** [comment]
> <img alt="image" width="1279" src="https://private-user-images.githubusercontent.com/17328586/375777440-0577f829-512a-4353-99f0-26201b773304.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2OTUzNjIsIm5iZiI6MTcyODY5NTA2MiwicGF0aCI6Ii8xNzMyODU4Ni8zNzU3Nzc0NDAtMDU3N2Y4MjktNTEyYS00MzUzLTk5ZjAtMjYyMDFiNzczMzA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDAxMDQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhYmM1MTgwMmY5ZjJhNWQxNGY4NGYyMTRjZDY5NjI0ZGViYjEwZDc0YjFlMmU3ZDA2YTBhNjliNGNiZTNkOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lmG4kBTq4FrsRFKjk7QPQKGyjJpAmlzCDOAj_euGflI"> <img alt="image" width="390" src="https://private-user-images.githubusercontent.com/17328586/375775059-7f06aa46-ddbf-4835-a101-0b2dfa6f6127.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2OTUzNjIsIm5iZiI6MTcyODY5NTA2MiwicGF0aCI6Ii8xNzMyODU4Ni8zNzU3NzUwNTktN2YwNmFhNDYtZGRiZi00ODM1LWExMDEtMGIyZGZhNmY2MTI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDAxMDQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkYjNjNWNlMGY3NmU4NGYwMTYwMGNmYWQyMzJkZjcwZTNjZDY1YTU3MzJlMDI0NTE4YTBkMjEyZjRkOGQ0NzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t_QxERz0LgWmJWRuFrucdJ7pPVpwt7UGcMiqQ_AA5sM">
> 这样呢？

现在的排布空间利用率太低了，而且确实不如之前版本的那么规整和一目了然，希望能改回之前的样子😅

**Comment by Lovefish** [comment]
> > @kunish
> > 中文是宋体不是雅黑，颜色组合也很奇怪，其实也可以把这些奇奇怪怪的主题都删掉，只留一套精心设计的明暗主题就行
> > ![673e054f8abb4d6372de1f30f2e4940f.jpeg](https://camo.githubusercontent.com/cece7feb476eefeff9646b844bd6eaeecfd1af4a01f771c8f6768305e3bbc96a/68747470733a2f2f6963652e66726f7374736b792e636f6d2f323032342f31302f31312f36373365303534663861626234643633373264653166333066326534393430662e6a706567)
> 
> winter/sunset 作为明暗主题就挺棒的

主题这种事情没必要特别保留什么，而且主题非常简单，就只是配色而已，保留着让别人自己选择就好，干嘛要删掉？

**Comment by Lovefish** [comment]
现在手机端两列排布非常的杂乱无章，确实是没有之前的看着舒服。

**Comment by fildunsky** [comment]
I totally agree, new UI changes are awful. Can we have gradients back, 2 columns back and old layout for texts and icons inside the proxy card back please?

**Comment by kunish** [comment]
试一下这个，https://github.com/MetaCubeX/metacubexd/pull/1080

另外，可以去新帖讨论，提建议 https://github.com/MetaCubeX/metacubexd/issues/1077

**Comment by junjiego2** [comment]
> 友情提醒一下楼中各位，新版非常ok，快来升级
> 
> https://github.com/MetaCubeX/metacubexd/releases/tag/v1.164.0

升级了，发现节点卡片的渐变效果没了，变成纯色，在某些浅色主题下，高饱和度的卡片好刺眼，例如 winter，还是退回 V.1.152.0 了
![image](https://github.com/user-attachments/assets/99dc8a85-f436-45b8-9b53-4a459c1299b0)
