### ISSUE TITLE
[Feature] 去除节点卡片的测速按钮，改为点击延迟测速

### ISSUE THREAD

**Issue by Plutonium141** [MetaCubeX/metacubexd#1077]
- 测速按钮要占很大一块空间，但是实际上却没什么用，可以去掉按钮改为点击延迟数字进行测速。

- 想要继续凹还可以把延迟的单位去掉，因为懂的人不用单位也知道是延迟，不懂的人有没有单位也都不懂，另外很多游戏延迟一栏也都是没有单位的，所以去掉应该没有什么影响。省下来的空间应该足够让协议类型标签和延迟处于同一行中

- 节点卡片的1rem的内边距太大了，代理组1rem还可以，但是铺满屏的节点卡片就不怎么合适，个人实测0.5rem看着挺好的

- .card-body类带了0.5rem的间距，实际上0rem的间距也不丑

![效果图](https://github.com/user-attachments/assets/84937c66-7b89-4aa2-9ee7-0e107bb5330f)

- udp xudp 还有ipv6也可以使用两种不同颜色的“U”和“6” 的标签显示，完整的信息可以在tooltip里显示

另外提个Feature，可以右键或长按节点卡片显示一个节点详细信息的弹窗，api的数据里还有很多信息可以显示在这里，比如延迟测试的历史记录，tfo、udp和xupd的支持情况等

**Comment by Lovefish** [comment]
这个确实可以，每一个节点都有相同的一个按钮，感觉是有点重复和多余。
不过可以做一个开关，看是否要显示。

**Comment by kunish** [comment]
延迟测试失败的节点咋整，显示 0？

**Comment by kunish** [comment]
<img width="1282" alt="image" src="https://github.com/user-attachments/assets/f653929a-16e8-4405-99b9-d62db99b9320">

还是感觉 0.5 rem 有点不得劲

**Comment by kunish** [comment]
<img width="1281" alt="image" src="https://github.com/user-attachments/assets/c6a281e8-de2f-4340-8a50-158914ef9353">

**Comment by devome** [comment]
我觉得信息密度还可以再提高点，协议、udp/ipv6支持情况和延迟完全可以缩小字体显示在一行中。对于一个机场而言，基本上协议都是那一种，用大标签意义不大。
实在一行放不下，可以考虑协议、udp/ipv6等支持情况全部用单字母小图标显示。另外在分组那里加个过滤来过滤不同的支持情况，顺便还可以以此作为图例，解释图标含义。

**Comment by kunish** [comment]
udp/ipv6 现在已经很小了，0.75 rem，rem 是根据浏览器字体计算的，一般是 16，16 像素 * 0.75 = 12 像素，这已经是浏览器的建议最小字体尺寸了

**Comment by devome** [comment]
> udp/ipv6 现在已经很小了，0.75 rem，rem 是根据浏览器字体计算的，一般是 16，16 像素 * 0.75 = 12 像素，这已经是浏览器的建议最小字体尺寸了

现在主要是用来打标签的色块看起来比较大，然后视觉上比较大。

**Comment by kunish** [comment]
我对 udp / ipv6 这种东西是不是显示无感，也可以考虑直接去掉，放在工具提示（tooltip）里

**Comment by devome** [comment]
> 我对 udp / ipv6 这种东西是不是显示无感，也可以考虑直接去掉，放在工具提示（tooltip）里

也可以，我也对此无感，使用时也不会纠结这个信息。

**Comment by kunish** [comment]
telegram 投票：https://t.me/c/1166154022/1078372

**Comment by devome** [comment]
@kunish tg群链接是什么，不进群组打不开投票链接。

**Comment by kunish** [comment]
> @kunish tg群链接是什么，不进群组打不开投票链接。

群主设置了 private，我也魔法

**Comment by kunish** [comment]
1. 展开讲讲
2. 很有必要么？
3. zkjj
4. 已删
5. 已开
6. 褒贬不一

**Comment by kunish** [comment]
1. 图表有人用，还有挪到代理页以后，移动端会开骂
2. 没意见

**Comment by kunish** [comment]
我可以想办法把顶上的 stats 紧凑点显示出来，但是图表不建议去掉，如果图表单独放一个页面，还得再考虑布局，不能太空

**Comment by kunish** [comment]
> 图表扔到设置页面去

那设置页又开始满了

**Comment by kunish** [comment]
设置页有一个跟连接 stats 相关的，代理页也有一个跟连接 stats 相关的，很割裂

**Comment by kunish** [comment]
let me see

**Comment by Lovefish** [comment]
> 总结一下功能建议：
> 
> 1. /overview 页直接删掉，图表毫无意义根本没人看，速度流量直接挪到 /proxies 页，还更方便了
> 2. 所有页面都可以接收处理 hostname 和 secret 参数，这样可以直接进入目标页面，不用再多余的手动切换
> 3. 奇奇怪怪的主题都删掉，只留一套精心设计的明暗主题
> 4. ~IPv6 相关的东西都删除掉，没有意义~
> 5. ~autoCloseConns 应该默认开启~
> 6. proxiesPreviewType 应该删除，只显示点阵，只有点阵是有意义的，其他选择都没有意义
> 
> Bugs：
> 
> 1. ~/rules 页的搜索框和 /conns /logs 页的dom结构不统一，没在同一行~
> 2. Firefox 下折叠展开动画丢失
> 3. Firefox 下字体显示为宋体，正常情况应该是雅黑
> 4. Twemoji 可以在 Firefox 中默认关闭，在 Chrome 系中默认开启

"Overview根本没人看"，不知道你是展开了怎样的调查研究，才得出这种结论的。
主题放得好好的，也不影响到你个人，干嘛要删掉？别人可以有选择的空间
IPV6没有意义，你又是做了怎样的调查？真是莫名其妙的
以上，不说在gitHUB，我以为进了某个小学生群呢。

**Comment by Lovefish** [comment]
> let me see

Poxy页面可以添加一个收起全部折叠的开关，毕竟有时候会打开多个group，一个一个折叠起来比较麻烦

**Comment by Lovefish** [comment]
> let me see

更新最新版之后侧边栏rules不见
![Screenshot_2024-10-13-05-24-22-824_me weishu kernelsu](https://github.com/user-attachments/assets/f806aac4-c3cc-4c56-bd06-3b6b80ecfcba)
还有选择节点之后ping值变得不可见（之前一两个版本还好

**Comment by toddyoe** [comment]
提个小bug，修改后国际化有点小问题
![image](https://github.com/user-attachments/assets/c8657094-8af0-4608-8970-978e29801eda)

**Comment by xuanranran** [comment]
这几天改的有点面目全非了
`v1.167.1`版本`规则`名称丢失，选择节点ping值隐约不可见
IPv6还是有作用的，有利于那些有v4和v6混合的订阅用户进行选择
节点类型可以做成 `节点协议|是否支持UDP/XUDP|是否支持IPv6` 简单就是 `SS|UDP|IPv6` 可以用大写，这样就好看许多
上面那位总结的，只适用于节点少 策略组少 以及规则少 的用户，那些动不动合并几个订阅超过几百上千的节点就不友好了，有些人还是喜欢搞那种精细分每个平台然后选择不同节点(我的策略组到达80+，也有人的策略组是到达100+的)
......后面待补充

**Comment by Lovefish** [comment]
显示udp和ipv6的重要性是高过协议的。
现在这两个东西反而不显示，只显示个协议，协议对我一点都不重要。
还是建议做个选项，让大家可以自由选择。起码我是需要udp和IPV6的，而具体是什么协议不在意，只要能正常连接就好

**Comment by xuanranran** [comment]
> 显示udp和ipv6的重要性是高过协议的。 现在这两个东西反而不显示，只显示个协议，协议对我一点都不重要。 还是建议做个选项，让大家可以自由选择。起码我是需要udp和IPV6的，而具体是什么协议不在意，只要能正常连接就好

可以不用添加开关的，协议旁边也是有位置的，添加了开关的话，默认状态下还是处于false，这样不同浏览器打开还是要多一个繁琐的步骤

**Comment by KuGouGo** [comment]
移动端代理处，网速显示和展开收起的箭头容易误触，点击后会显示分页已崩溃
