### ISSUE TITLE
[bug]代理组无法正常显示测速结果；

### ISSUE THREAD

**Issue by Fddh2012** [MetaCubeX/metacubexd#1192]
版本：1.173.1 / alpha-geb985b0

在代理提供者下是能看到节点测速情况：
![image](https://github.com/user-attachments/assets/70ff35a1-4fa8-4ac7-af7a-236eb59b29dc)
![image](https://github.com/user-attachments/assets/ff642a1c-faaa-4596-9d31-5305f87de311)

但是在代理组下却会看不到节点测速情况：
![image](https://github.com/user-attachments/assets/1c00eae3-12d1-4113-b952-47d02da7f6ab)
![image](https://github.com/user-attachments/assets/9ca7d21a-07c5-4f43-a80e-d21fdeffe0ce)

我的代理链是如下：
![image](https://github.com/user-attachments/assets/89731b49-ec6a-4333-9f08-acebb79856a4)
但是在这里却能看到测速记录。
![image](https://github.com/user-attachments/assets/340b89e4-fdb6-4a37-9542-453483722304)

**Comment by njzydark** [comment]
代理组是不是有配置单独的测速 url

**Comment by haohaoget** [comment]
我也是这个问题，确实配置了自己的测速url

**Comment by njzydark** [comment]
可以考虑先用上个版本（之前的版本虽然有显示， 但不是你配置文件里的测速 url 里的延迟），这个问题修复中

**Comment by Fddh2012** [comment]
> 可以考虑先用上个版本（之前的版本虽然有显示， 但不是你配置文件里的测速 url 里的延迟），这个问题修复中

单纯只是面板问题其实就无所谓，内核正常工作会自动切换就好。
