### ISSUE TITLE
辛苦大佬，请问能否给选项列表都添加上测速显示的？？

### ISSUE THREAD

**Issue by Jing0807** [MetaCubeX/metacubexd#151]
![mmexport1693966474251.png](https://github.com/MetaCubeX/metacubexd/assets/106135906/8eb916d6-c30c-4443-bccc-8a3eaf585a84)

红框内容

**Comment by Jing0807** [comment]
![mmexport1693966951190.png](https://github.com/MetaCubeX/metacubexd/assets/106135906/bd53385b-905b-474f-97a5-17ddc4a1bd84)

还是说我要在config里面添加参数？！

**Comment by Zephyruso** [comment]
刚刚测速有点问题，现在修好了，测速一下应该就有了

**Comment by Jing0807** [comment]
> 刚刚测速有点问题，现在修好了，测速一下应该就有了

![mmexport1693970228445.png](https://github.com/MetaCubeX/metacubexd/assets/106135906/372ec63b-ff88-4886-a838-fbd1a5589c90)

感谢大佬，现在有了，完美
