### ISSUE TITLE
[Feature Request] 添加开关 "规则和规则提供者同列渲染" 

### ISSUE THREAD

**Issue by ShoukakuChuuCC** [MetaCubeX/metacubexd#158]
效果类似于“节点双列渲染”，将节点和节点提供者放在同一列
希望规则也适配一下，只有一个规则提供者的情况下，看着不够整体
![image](https://github.com/MetaCubeX/metacubexd/assets/38343280/1e8c97ba-598f-4837-af3c-6598b07d9996)

**Comment by Zephyruso** [comment]
已添加 https://github.com/MetaCubeX/metacubexd/commit/7e2fe6acb0d2bc879cd724cfda7d80924abd5d40
