### ISSUE TITLE
更新全部代理的按钮位置放的太远了

### ISSUE THREAD

**Issue by iKun10001** [MetaCubeX/metacubexd#168]
pc上操作感觉不是很方便
1拉过来左边 挨着代理的选项
2要不直接把这个代理提供者  右边的的这个数量 做成更新按钮 用一个转圈箭头包裹着

  
代理   全部的那个选项 可以弄个设置 可选  代理和代理提供者分开展示 或者 展示全部  么  强迫着有点看不惯那个现在的三个按钮 ···

**Comment by iKun10001** [comment]
还有就是  代理 放在左边  代理提供者放在右边   我感觉代理 是更常用到的选项  感觉这样比较合理一点点

**Comment by iKun10001** [comment]
> pc上操作感觉不是很方便 1拉过来左边 挨着代理的选项 2要不直接把这个代理提供者 右边的的这个数量 做成更新按钮 用一个转圈箭头包裹着
> 
> 代理 全部的那个选项 可以弄个设置 可选 代理和代理提供者分开展示 或者 展示全部 么 强迫着有点看不惯那个现在的三个按钮 ···

或者  更新全部按钮 做成一个矩形的 转圈图标 把 代理提供者的数量 包裹着  类似  贪吃蛇那样 感觉实现会比较麻烦 不过这样感觉挺秀的

**Comment by Zephyruso** [comment]
![image](https://github.com/MetaCubeX/metacubexd/assets/127948745/5b66fdd5-0b45-4d6f-993e-f763235c453c)
先暂时拉过来的吧
