### ISSUE TITLE
[优化请求] 过滤展开的排版

### ISSUE THREAD

**Issue by ShoukakuChuuCC** [MetaCubeX/metacubexd#170]
![image](https://github.com/MetaCubeX/metacubexd/assets/38343280/224ec936-bc7b-4b25-8daa-1ed99a4e9d87)
展开后左侧空了很长一栏，能优化一下吗？

**Comment by kunish** [comment]
你会发现这个空间布局是为了跟顶上的表头对齐

**Comment by ShoukakuChuuCC** [comment]
> 你会发现这个空间布局是为了跟顶上的表头对齐

噢噢，但会不会太空了点

**Comment by kunish** [comment]
不对齐就不合理了
