### ISSUE TITLE
[feature request] 更多的`自动断开连接`选项

### ISSUE THREAD

**Issue by iKun10001** [MetaCubeX/metacubexd#173]
这个可以改成  仅断开 正在连接中的连接吗  比如 奈菲分组选择新加坡节点 在奈菲分组换了个香港节点 就只断开奈菲规则相关的连接  而不是其他全部连接都断开呢

**Comment by Larvan2** [comment]
可能这么改好一些
[Break When Proxy Change](https://docs.cfw.lbyczf.com/contents/breakconn.html#break-when-proxy-change)
None：默认值，不进行打断
Chain：打断所有 chains 中包含此策略组的连接
All：打断所有连接

**Comment by Zephyruso** [comment]
已更改实现为断开对应策略组链接 暂未实现加入断开全部链接的选项

**Comment by iKun10001** [comment]
> 已更改实现为断开对应策略组链接 暂未实现加入断开全部链接的选项

那个选项感觉不太需要的样子 就保持现在这个断开对应连接 就挺好  大佬辛苦
