### ISSUE TITLE
[Feature Request] 希望支持单节点测速

### ISSUE THREAD

**Issue by kogekiplay** [MetaCubeX/metacubexd#232]
![image](https://github.com/MetaCubeX/metacubexd/assets/46434871/621ed553-c787-4b00-a464-d76f5cf06c72)

如图，谢谢大佬

**Comment by kunish** [comment]
OK，等有时间了加上

**Comment by kunish** [comment]
抱歉该功能目前暂时没有 API 支持，经过一番讨论之后我们决定暂时不做支持
