### ISSUE TITLE
This dashboard is using too much RAM over time

### ISSUE THREAD

**Issue by hillz2** [MetaCubeX/metacubexd#234]
This dashboard is using too much RAM over time if you keep it open for like an hour or 2. It can use up to 4GB of RAM on my pc. Fix it please

**Comment by kunish** [comment]
Could you please provide some more information? It can greatly help us to investigate the root cause of this issue.

**Comment by hillz2** [comment]
I'm not a programmer but I'll try my best.

**How to reproduce the problem:**
1. Open Metacubex Overview page on google chrome
2. Leave the page open and switch to browse another page
3. Wait like an hour or so and open the chrome's task manager, you'll see that the RAM on metacubex has gone way up.

I think it has to do with the graphs & javascript on the Overview page.

**Comment by hillz2** [comment]
Thanks for fixing the issue, honestly this dashboard looks so much better than YACD, I hope the openclash developer replaces YACD with this one

**Comment by kunish** [comment]
Thank you for the kind words. Maybe someone and someday there will be a PR for openclash :)

**Comment by hillz2** [comment]
@kunish I'm still having the same problem on the connection tab, please fix it.

**Comment by hillz2** [comment]
The logs tab as well, the ram usage just keeps growing if you leave it open over time.

![2023-09-30-212421_1920x1017_scrot](https://github.com/MetaCubeX/metacubexd/assets/25127225/e677d213-a771-497a-b48a-0df606908b36)
