### ISSUE TITLE
日志不受config.yaml的控制吗？

### ISSUE THREAD

**Issue by nkta3m** [MetaCubeX/metacubexd#245]
在config.yaml设置日志为silent,界面里确实info,是要单独设置？能不能默认读取config.yaml的设置?

**Comment by kunish** [comment]
可以

**Comment by nkta3m** [comment]
是要等更新还是自己在哪里设置?

**Comment by kunish** [comment]
等更新，可以自己先在日志页面的设置弹窗里设置

**Comment by nkta3m** [comment]
ok,谢谢

**Comment by kunish** [comment]
想了一下，感觉这个没必要跟随 config.yaml 的控制，页面上可以控制拿到的日志等级返回

**Comment by nkta3m** [comment]
好吧，但是我还是觉得初始化应该以config为准
