### ISSUE TITLE
filter by client ip combo box

### ISSUE THREAD

**Issue by lux5am** [MetaCubeX/metacubexd#246]
please add filter by client ip combo box like in yacd/dashboard
![Screenshot_20230919-192956_Kiwi Browser](https://github.com/MetaCubeX/metacubexd/assets/110870661/7fa0194d-a46e-40a1-837e-cc515df552d6)

also connection list missing "Sniff Host" column.
and sorting the columns in mobile view is very challenging.

**Comment by kunish** [comment]
Good idea, but maybe somewhat complicate to implement. So be patient, I'll find some time to take a overall look of this feature

**Comment by lux5am** [comment]
thanks fam 🙏🏾
