### ISSUE TITLE
节点排序改成延迟从小到大 测试后不会按照从小到大排序

### ISSUE THREAD

**Issue by iKun10001** [MetaCubeX/metacubexd#251]
需要重新开关一下节点列表  才会按照设置排序

**Comment by iKun10001** [comment]
感觉点开节点列表时   同时展开两列 不太优雅     

节点列表的  测试延迟按钮  可以拉到 左边列表名旁边吗   那样更便捷一些  

端口设置的那个框  感觉真的没必要弄那么大  弄个 小框  甚至直接 挤到一起 弄成一行   感觉都会更简洁美观

**Comment by kunish** [comment]
重新开关一下节点列表才能按照设置排序，这个问题没有复现

端口设置的那个框，考虑到移动端适配，现在会在小屏幕上 3 个一行，大屏幕上 5 个一行

**Comment by kunish** [comment]
还有点开节点列表的时候并不是同时展开两列，是不是好久没有更新了
