### ISSUE TITLE
设置界面按钮的位置是否可以调整？

### ISSUE THREAD

**Issue by nkta3m** [MetaCubeX/metacubexd#263]
![2023-09-22 10_17_58-Window](https://github.com/MetaCubeX/metacubexd/assets/13484700/d705de9c-6fac-4e8f-a9ff-ee77d9f85591)

我觉得更新核心属于要谨慎操作的，应该单独放置，以免误操作

**Comment by kunish** [comment]
<img width="848" alt="image" src="https://github.com/MetaCubeX/metacubexd/assets/17328586/ed32993d-f19e-4637-8669-6117a8630413">

这样？

**Comment by kunish** [comment]
<img width="859" alt="image" src="https://github.com/MetaCubeX/metacubexd/assets/17328586/1ac87650-6b3d-4bdd-87d3-11ed245b4e64">

加了点颜色

**Comment by nkta3m** [comment]
我的理解应该是重启配置-清空fakeip-更新GEO-重启核心 这属于一个逻辑，然后更新核心是另外一个逻辑了
