### ISSUE TITLE
[Feature Request] TUN相关设置

### ISSUE THREAD

**Issue by Xinyu-Wu-0000** [MetaCubeX/metacubexd#267]
希望像yacd-meta面板一样支持TUN模式相关设置。

**Comment by kunish** [comment]
<img width="802" alt="image" src="https://github.com/MetaCubeX/metacubexd/assets/17328586/633372e0-a003-4008-a3ce-a569fc2ab859">

<img width="404" alt="image" src="https://github.com/MetaCubeX/metacubexd/assets/17328586/a41d938c-e4b3-4db4-b69d-8988c48bfd8e">
