### ISSUE TITLE
1.113.0 测试问题

### ISSUE THREAD

**Issue by hux555** [MetaCubeX/metacubexd#281]
- name: ♻️ 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - v2rayse_test_1
      - v2rayse_test_2
      - v2rayse_test_3
      - defaultName_1
      - v2rayse_test_4
      - defaultName_2
      - defaultName_3
      - Hys-1.2.3.4
      - test
      - defaultName_4

  url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
这块设置在里面不生效吗，观察了很久  只能点测速图标才会进行测速， 也不会自动切换到低延时节点上面去    刷新网页的延时结果也不会变化

**Comment by kunish** [comment]
用新版本再试一下？
