### ISSUE TITLE
[BUG] 延迟测试工作不正常

### ISSUE THREAD

**Issue by Plutonium141** [MetaCubeX/metacubexd#287]
1：点击代理组的延迟测试按钮后，测试结果只会显示一下然后就会变回页面打开时的延迟，已知在1.100.1以前没有这个问题

2：单节点延迟测试没有效果，浏览器控制台会报404

3：手动切换节点时，所有的延迟测试按钮都会闪烁一下，看着很怪

**Comment by kunish** [comment]
现在呢

**Comment by Plutonium141** [comment]
> 现在呢

现在单节点延迟测试浏览器不会报404了 但是不会显示结果，其他问题则没有改变

**Comment by kunish** [comment]
更新一下内核

**Comment by Plutonium141** [comment]
> 更新一下内核

感谢  更新内核后问题解决了
但是切换节点时测试图标还是会抖动一下，不过这个问题可以以后再说

**Comment by hillz2** [comment]
@kunish I'm having the same problem, can you write the solution in English? Google translate isn't very reliable
