### ISSUE TITLE
当 rules 里的 geosite 和 geoip 有重名时，“规则”内有显示错误

### ISSUE THREAD

**Issue by DustinWin** [MetaCubeX/metacubexd#313]
**版本：** 1.121.0
**问题：**  
当 rules 里的 geosite 和 geoip 有重名时，如图：  
<img src="https://github.com/MetaCubeX/metacubexd/assets/45238096/61fc4ac2-2852-4405-9a97-469d55eb50f7" width=60%/>
进入“规则”，可以看到有两个一模一样的 `geosite:private` 和 `geosite:cn`， geo 类型、规则数和代理名都不正确  
<img src="https://github.com/MetaCubeX/metacubexd/assets/45238096/2473038c-1243-43cb-a550-4ef60ce3a59b" width=60%/>

**Comment by kunish** [comment]
跟面板有什么关系

**Comment by DustinWin** [comment]
> 跟面板有什么关系

之前一样的 rules，面板显示是正常的。由于版本刷新的太快，不清楚是从哪个版本开始出现该问题的，在我举的例子里，“规则”页面中最下面的两个应该是 GeoIP。

**Comment by DustinWin** [comment]
> > 跟面板有什么关系
> 
> 之前一样的 rules，面板显示是正常的。由于版本刷新的太快，不清楚是从哪个版本开始出现该问题的，在我举的例子里，“规则”页面中最下面的两个应该是 GeoIP。  
**使用的 Meta 核心版本：**v1.16.0

**Comment by DustinWin** [comment]
> 跟面板有什么关系

[Yacd-meta 面板](http://yacd.metacubex.one)显示就是正常的  
<img src="https://github.com/MetaCubeX/metacubexd/assets/45238096/aa3d1fe1-6e74-4a28-b7f7-35abe6fe8181" width=60%/>
