### ISSUE TITLE
求问如何把  metacubexd 部署在本地？

### ISSUE THREAD

**Issue by MelodyUSA** [MetaCubeX/metacubexd#314]
想要把 metacubexd 面板部署在本地的 linux 上，但项目的 README.md 关于这部分只有这样：
![sdafsdf|400](https://i.imgur.com/rvYHR8t.png)

**Comment by Sz-Yuan** [comment]
不知道你现在还需不要本地部署，但是有两个简单的方法可以本地部署。
使用vscode插件可以在vscode中进行暂时本地部署访问：

1. 下载发行版中的[compressed-dist.tgz](https://github.com/MetaCubeX/metacubexd/releases)
2. 解压到某个本地文件夹
3. 使用vscode打开该文件夹
![image](https://github.com/MetaCubeX/metacubexd/assets/143470829/c8ead82d-f5aa-4300-8627-d964593fee37)
4.下载插件fiveserver
![image](https://github.com/MetaCubeX/metacubexd/assets/143470829/49d76782-95c4-4955-9b38-44870f5404a4)
5.进入index.html,右键点击Open with Five Server
![image](https://github.com/MetaCubeX/metacubexd/assets/143470829/8021503f-9c37-4741-919f-831ca5b7e6d2)
这将会打开你的默认浏览器运行出该界面
![02dad519753f2a319f7daf63c3e646a4](https://github.com/MetaCubeX/metacubexd/assets/143470829/b4b65359-ec3c-49b5-a3aa-c21a9f330703)

**Comment by Sz-Yuan** [comment]
二：
使用http-server
1.下载安装[nodejs](https://nodejs.org/zh-cn)
2.安装http-server
确保nodejs安装成功后在cmd运行【npm install http-server -g】指令，表示安装到全局，之后所有文件夹路径下输入http-server都可以使用。
![image](https://github.com/MetaCubeX/metacubexd/assets/143470829/b889c52f-62d1-4b31-8ff9-cfd531cc37a6)
3.转到你解压出compressed-dist.tgz的文件夹，右键点击在终端打开
![image](https://github.com/MetaCubeX/metacubexd/assets/143470829/b0a68376-6123-4f7c-b754-f8b16091a532)
4.如果右键没有在终端中打开，那么你可以先打开终端，如果你解压后的文件在D盘，运行指令【D:】回车，然后执行指令【cd xxxx(xxx表示你存放解压后文件夹的地址)】，转到文件夹所在地址后，运行【http-server -p xxxx(xxxx表示你要开启的端口)】,也可以直接使用【http-server】指令，默认端口一般为8080。
5.如果所有步骤正确会出现如下界面
![image](https://github.com/MetaCubeX/metacubexd/assets/143470829/28c725fb-6c9b-438b-af60-d644a3e3834d)
访问cmd中的地址
![878ab167ad1bb8264e54865c30ffcb2f](https://github.com/MetaCubeX/metacubexd/assets/143470829/df5007ae-9ea6-49d5-9715-370c1683198c)
第一个为局域网/公网访问地址，如果你没有公网，那么别人是无法访问的，
第二个为本地访问地址，只有本机可以访问
6.以图片为例，访问 【xxx/index.html(xxx表示cmd中的地址)】  或者Ctrl+左键点击访问地址，即可进入web控制界面。
![d269dd597fb6845bea5989d4eaa13aef](https://github.com/MetaCubeX/metacubexd/assets/143470829/08c73652-6e98-401d-ae76-655725e52113)
7.在终端界面使用Ctrl+C即可关闭服务
![image](https://github.com/MetaCubeX/metacubexd/assets/143470829/9cd9b3e9-a402-43a7-9b59-3eb4d2cdf7f4)
8.可以使用bat脚本快捷打开web控制界面，在该文件夹内新建bat文件，
![image](https://github.com/MetaCubeX/metacubexd/assets/143470829/9c9b2305-b93a-4ef6-8476-d4a1dd5a6636)
输入以上内容，端口可以自定义。
之后双击bat文件即可运行http-server
