### ISSUE TITLE
on mobile view it's very hard to sort connection list's columns

### ISSUE THREAD

**Issue by lux5am** [MetaCubeX/metacubexd#320]
sometimes accidental tap will cause the column to move.
can we get a sorting area like in yacd?
picrel:
![Screenshot_20230930-080839_Kiwi Browser](https://github.com/MetaCubeX/metacubexd/assets/110870661/2725f5e1-037f-479e-b356-7457f84cd13f)
![Screenshot_20230930-080700_Kiwi Browser](https://github.com/MetaCubeX/metacubexd/assets/110870661/445a7cc8-808f-477a-85d3-a18ef4791a70)

**Comment by lux5am** [comment]
thanks for the update but unfortunately it's still very hard to move around. not touch friendly.

**Comment by kunish** [comment]
Feels bad to hear that, at least I tried. Maybe someone can come up a better solution for this.

**Comment by lux5am** [comment]
with a touch it's hard to drag. often it just grayed out without moving. sometimes it suddenly moved down/up randomly. or the list just scrolled up/down. it's chaotic. even with desktop view it's still unresponsive/unmoved.
