### ISSUE TITLE
expand/collapse icon doesn't appear in dark themes

### ISSUE THREAD

**Issue by lux5am** [MetaCubeX/metacubexd#324]
yes I confirm all dark themes don't have it. It's not black just don't exist. but clickable.
picrel:
![Screenshot_20231003-055607_Kiwi Browser](https://github.com/MetaCubeX/metacubexd/assets/110870661/0f644f04-060a-4cb4-9577-0d310f79e623)
![Screenshot_20231003-055423_Kiwi Browser](https://github.com/MetaCubeX/metacubexd/assets/110870661/ddc6174f-59ef-452b-a139-f69ddce11cf9)

**Comment by kunish** [comment]
not reproducible

**Comment by lux5am** [comment]
it's on kiwi browser for Android. I tried Firefox seems to be ok. weird. no extensions running.
