### ISSUE TITLE
关于策略组的疑问

### ISSUE THREAD

**Issue by yorunning** [MetaCubeX/metacubexd#330]
在分组内，url-test/fallback 仍然可以手动选择切换。预期的行为应当与 load-balance 策略一致，即禁止手动点击切换。在使用cfw/stash 等客户端时，url-test/fallback/load-balance 三种策略仅允许根据测速自动切换。

**Comment by RikudouPatrickstar** [comment]
这个是 meta 核心的特性，故意设计的，参考 https://github.com/MetaCubeX/Yacd-meta/issues/72
