### ISSUE TITLE
Overview 页面在不停地请求静态资源

### ISSUE THREAD

**Issue by RikudouPatrickstar** [MetaCubeX/metacubexd#339]
浏览器开发者工具截图：

![image](https://github.com/MetaCubeX/metacubexd/assets/68163551/d62d9952-17f5-4516-85b2-9bdea99312b0)

**Comment by RikudouPatrickstar** [comment]
刷新几次页面之后触发

**Comment by lux5am** [comment]
I can confirm the issue. after refreshing the page it keep downloading the fonts endlessly.

**Comment by kunish** [comment]
没复现成功，有稳定的办法么

**Comment by kunish** [comment]
Can't reproduce this issue on my side, can we find a steady way to reproduce it?

**Comment by lux5am** [comment]
even I can reproduce it on mobile immediately

open XD
open devtools
on XD open connections
open overview
refresh XD

![Screenshot_20231009-024759_Kiwi Browser](https://github.com/MetaCubeX/metacubexd/assets/110870661/01956d58-e4ec-46f8-82ce-e2dd9f4c7745)
![Screenshot_20231009-024414_Kiwi Browser](https://github.com/MetaCubeX/metacubexd/assets/110870661/712c1111-8044-4e88-9747-39f3da824ec1)

**Comment by RikudouPatrickstar** [comment]
是的，切换页面再刷新也可以复现。我这边现在直接在 Overview 页面刷新就出现这个情况了

**Comment by RikudouPatrickstar** [comment]
https://github.com/MetaCubeX/metacubexd/assets/68163551/f052f2b0-1f7d-46ea-baae-004228868172

**Comment by kunish** [comment]
still can't reproduce this issue

**Comment by kunish** [comment]
Remote desktop session with @RikudouPatrickstar minutes before, after some digging, we can reproduce this issue on chromium based browser, such as Microsoft Edge and Google Chrome, but doesn't seem to have any issue whatsoever on firefox. Maybe it's an issue related to apexcharts rendering in svg, we still don't know yet. But after disabling the apexcharts fixes this issue.

**Comment by RikudouPatrickstar** [comment]
用最新版的浏览器试了下最近的版本，没有这个问题了
