### ISSUE TITLE
请教下大佬们，metacubexd如何部署到render中

### ISSUE THREAD

**Issue by wisinfun** [MetaCubeX/metacubexd#369]
对前端知之甚少，自己尝试了多次，静态网站和网页服务都尝试了，都失败了，希望有佬哥能解答下
<img width="1680" alt="image" src="https://github.com/MetaCubeX/metacubexd/assets/41355260/5c76457a-c177-4083-a382-15086283d1a6">
![image](https://github.com/MetaCubeX/metacubexd/assets/41355260/4f28cd69-2b19-4430-8bac-c730b2b987ce)

**Comment by kunish** [comment]
为什么要自己部署呢
