### ISSUE TITLE
代理界面测速那里，希望增加一个标记上游代理是否支持 ipv6 的图标。

### ISSUE THREAD

**Issue by arkxfly** [MetaCubeX/metacubexd#392]
找个纯 ipv6 的检测地址测速一下。

https://github.com/MetaCubeX/Clash.Meta/issues/794#issuecomment-1769815522

**Comment by kunish** [comment]
并不能实现

**Comment by kunish** [comment]
面板这个功能，代码怎么写？

**Comment by kunish** [comment]
那你提个 PR 吧
