### ISSUE TITLE
[Feature Request] 在Firefox浏览器中默认不使用 Twemoji Mozilla 字体

### ISSUE THREAD

**Issue by pd12bbf7608ae1** [MetaCubeX/metacubexd#406]
在Firefox浏览器中，节点的地区旗帜可以正常显示，并且在Firefox中启用Twemoji Mozilla字体会导致问题 #394 ，已经复现。

Firefox:
![firefox](https://github.com/MetaCubeX/metacubexd/assets/33011786/fed9b077-f538-45ed-908f-e43ec693f7cf)

Edge:
![edge](https://github.com/MetaCubeX/metacubexd/assets/33011786/295915a4-fc61-485f-8424-e2fc0d03d1ef)

建议在初始化时，当前浏览器为Firefox时默认不使用 Twemoji Mozilla 字体

**Comment by kunish** [comment]
设置里有选项，请关闭
