### ISSUE TITLE
规则页解析太慢

### ISSUE THREAD

**Issue by RikudouPatrickstar** [MetaCubeX/metacubexd#413]
metacubexd 版本 1.125.0，规则有 7000 多条，CLash API 能在 47ms 返回数据，但页面解析需要 10s 左右。同样的规则用 yacd，页面能瞬间加载出来

![image](https://github.com/MetaCubeX/metacubexd/assets/68163551/cb5af275-d0f7-404e-9e34-73249a866308)

**Comment by Xarth-Mai** [comment]
+1

**Comment by devswork** [comment]
共1.6万条规则，进入 Rules 页5秒后chrome报错，内存溢出。
metacubexd 版本：1.128.1
clash.meta 版本：alpha-55255fa
centos7 操作系统

**Comment by devswork** [comment]
1.6万规则下，测试 yacd、dashboard 面板的规则页(Rules)没有问题，metacubexd 会卡死。

**Comment by kunish** [comment]
你们的规则数量多的有点离谱，现在这页面还没有做虚拟列表，所以相当于要一次性画全部的规则，不卡是不可能的

**Comment by KarlLee830** [comment]
> 你们的规则数量多的有点离谱，现在这页面还没有做虚拟列表，所以相当于要一次性画全部的规则，不卡是不可能的

如果在clash里写了广告拦截等规则的话，规则数量是会比较多的。看了下我这里有68200条规则。Yacd和官方dashboard都能“秒开”，metacubexd打开后Chrome标签页会卡死然后Out of Memory直接崩溃。
期待尽快改进一下吧，还是比较影响使用体验。

**Comment by devioa** [comment]
这个问题大概什么时候能修复呀，现在规则基本上都是几万条了吧

**Comment by Talaxy009** [comment]
+1
