### ISSUE TITLE
使用type: url-test,后，在UI节点还是能手动选择节点.

### ISSUE THREAD

**Issue by lkxlzx** [MetaCubeX/metacubexd#430]
使用type: url-test,后，在UI节点还是能手动选择节点.
我记得如果用这个后会自动选择延迟最低的节点，怎么设置后进UI在节点哪里还是能手动选择呢。

**Comment by xubai2001** [comment]
> 使用type: url-test,后，在UI节点还是能手动选择节点.
> 
> 我记得如果用这个后会自动选择延迟最低的节点，怎么设置后进UI在节点哪里还是能手动选择呢。

meta的url-test是可以手动选择的
