### ISSUE TITLE
区分同一个server的两个不同订阅

### ISSUE THREAD

**Issue by XinyuWuu** [MetaCubeX/metacubexd#446]
当在同一个机场使用两个账户购买两份不同订阅时，两个订阅指向同一个服务器，但用户是不一样的，希望能够区分一下，这样两份订阅才能有双倍的在线设备限制。现在选择一个节点，对应的另一个节点也被选上了，不知道是底层不区分还是界面问题：
![image](https://github.com/MetaCubeX/metacubexd/assets/57612792/b28ac3b5-60f7-4806-bb18-706afbdd0d4d)

**Comment by Xinyu-Wu-0000** [comment]
> 你这延迟好低，推荐下🤣

https://liangyuandian.club/#/login
https://sspanel.npv4.com/auth/login

别看延迟低，其实也就一般🤣
