### ISSUE TITLE
希望增加显示当前连接的后端，以及快捷切换后端。

### ISSUE THREAD

**Issue by arkxfly** [MetaCubeX/metacubexd#448]
当有多个后端的时候，不知道当前看的是那个后端的数据，要从开发者模式看网络请求。手机版的话，只能切到设置界面，重新登录了。

- 希望出个鼠标悬浮 logo 就能看到当前后端 ip。

目前切换后端只能先到设置界面再切，不够方便。
- 希望点击 logo 就可以到登录界面。

**Comment by DanielYWoo** [comment]
请问如何切换后端？我没有找到

**Comment by mokeyish** [comment]
我用的是这个 #472 ，未合并，需要自行构建。官方好像在最下面，我觉得太占空间了，也不好看。
