### ISSUE TITLE
添加https后端失败

### ISSUE THREAD

**Issue by muink** [MetaCubeX/metacubexd#473]
我用nginx为metacubexd配置了反向代理, 使其页面支持https
但是添加后端时却返回404
同样的配置, 使用yacd-meta却可以正常使用, 请问有什么解决办法吗

sing-box:
``` sing-box
{
	"experimental": {
		"clash_api": {
			"external_controller": "[::1]:9090",
			"external_ui": "/var/run/homeproxy/ui",
			"secret": "aacceebd-5555-6666-6666-261689827a1b",
			"store_mode": true,
			"store_selected": true,
			"cache_file": "/etc/homeproxy/clash_cache.db"
		}
	}
}
```
nginx:
``` nginx
location /homeproxy/ {
	proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto $scheme;
	proxy_pass http://localhost:9090/;
	proxy_redirect default;
	proxy_set_header Upgrade $http_upgrade;
	proxy_set_header Connection upgrade;
	proxy_set_header Connection "keep-alive";
}
```
![1](https://github.com/MetaCubeX/metacubexd/assets/7929014/0b09a08a-a940-4e15-9558-1f6fc5f3f0f9)

**Comment by ericjuice** [comment]
api需要单独代理，得有2条，我的后端地址是55555端口，这样配置就可以。
```nginx
location ^~ /api/ {
    proxy_pass http://127.0.0.1:55555/; 
    proxy_set_header Host $host; 
    proxy_set_header X-Real-IP $remote_addr; 
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
    proxy_set_header REMOTE-HOST $remote_addr; 
    proxy_set_header Upgrade $http_upgrade; 
    proxy_set_header Connection "upgrade"; 
    proxy_set_header X-Forwarded-Proto $scheme; 
    proxy_http_version 1.1; 
    add_header Cache-Control no-cache; 
}

location ^~ / {
    proxy_pass http://127.0.0.1:55555/ui/; 
    proxy_set_header Host $host; 
    proxy_set_header X-Real-IP $remote_addr; 
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
    proxy_set_header REMOTE-HOST $remote_addr; 
    proxy_set_header Upgrade $http_upgrade; 
    proxy_set_header Connection "upgrade"; 
    proxy_set_header X-Forwarded-Proto $scheme; 
    proxy_http_version 1.1; 
    add_header Cache-Control no-cache; 
}
```

**Comment by ericjuice** [comment]
> api需要单独代理，得有2条，我的后端地址是55555端口，这样配置就可以。
> 
> ```nginx
> location ^~ /api/ {
>     proxy_pass http://127.0.0.1:55555/; 
>     proxy_set_header Host $host; 
>     proxy_set_header X-Real-IP $remote_addr; 
>     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
>     proxy_set_header REMOTE-HOST $remote_addr; 
>     proxy_set_header Upgrade $http_upgrade; 
>     proxy_set_header Connection "upgrade"; 
>     proxy_set_header X-Forwarded-Proto $scheme; 
>     proxy_http_version 1.1; 
>     add_header Cache-Control no-cache; 
> }
> 
> location ^~ / {
>     proxy_pass http://127.0.0.1:55555/ui/; 
>     proxy_set_header Host $host; 
>     proxy_set_header X-Real-IP $remote_addr; 
>     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
>     proxy_set_header REMOTE-HOST $remote_addr; 
>     proxy_set_header Upgrade $http_upgrade; 
>     proxy_set_header Connection "upgrade"; 
>     proxy_set_header X-Forwarded-Proto $scheme; 
>     proxy_http_version 1.1; 
>     add_header Cache-Control no-cache; 
> }
> ```

然后后端地址填 https://your-domain/api即可

**Comment by muink** [comment]
还是不行, 变成502了

**Comment by muink** [comment]
一样的配置还是404

**Comment by ericjuice** [comment]
> 一样的配置还是404

不使用路径的反向代理，用子域名（比如mydomain.com）做反代。我之前用Yacd就是路径的不行。然后直接访问域名 https://mydomain.com ，地址就填 https://mydomain.com/api.
![image](https://github.com/MetaCubeX/metacubexd/assets/101324361/9509a1a4-0fc0-45ab-8f99-f338f495829c)

**Comment by muink** [comment]
我觉得还是这个dashboard有点问题
直接用curl都可以访问了
