### ISSUE TITLE
刷新测试延时出现问题

### ISSUE THREAD

**Issue by wangxi3709** [MetaCubeX/metacubexd#475]
最近出的几个版本都有同样问题，只要点击代理组的延时按钮，基本有大半的节点会挂掉，用回老版本不存在这个问题

**Comment by hbelove** [comment]
同样遇到点击代理组的延时按钮，部分没显示延迟。没显示的貌似都是没有ipv6的节点。单独点击没问题可正常显示。

**Comment by hbelove** [comment]
貌似singbox的问题，clash-meta内核没有这个问题

**Comment by sunr1s6** [comment]
> 最近出的几个版本都有同样问题，只要点击代理组的延时按钮，基本有大半的节点会挂掉，用回老版本不存在这个问题

請問需要安裝哪個版本的？ 我也是遇到同樣問題，只要按PING按鈕 節點就全灰了，但是用其他面板測速就是正常的。

**Comment by ClarkQAQ** [comment]
右上角设置里面删掉 IPV6 测试即可解决, 应该是 `https://api-ipv6.ip.sb` 那边 down 了

**Comment by adoyle-h** [comment]
碰到同样的问题，点击测速按钮后闪了一下延迟然后又没有了。
在设置里删掉 ipv6 的测速地址后正常。
建议 metacubexd 做个兼容处理，ipv6 测速失败不会影响 ipv4 的测速结果。或者 ipv4/ipv6 的测速结果分别列出来也行。
