### ISSUE TITLE
使用最新的版本，代理页面节点不显示，设置页面设置读取不到信息

### ISSUE THREAD

**Issue by lkxlzx** [MetaCubeX/metacubexd#500]
使用最新的版本，代理页面节点不显示，设置页面设置读取不到信息

![QQ图片20231211100615](https://github.com/MetaCubeX/metacubexd/assets/40789172/18cb6da6-4603-4e2a-9a38-61e2fb97c820)
![QQ图片20231211100622](https://github.com/MetaCubeX/metacubexd/assets/40789172/74d603c0-7dea-468f-82cf-2db86bc80a9f)
![QQ图片20231211100619](https://github.com/MetaCubeX/metacubexd/assets/40789172/88718831-c6ea-4db3-b9de-351bb4ee735e)

**Comment by zzstrive2007** [comment]
我也遇到了同样情况

**Comment by Hansen1018** [comment]
我的也是

**Comment by yzbleaf** [comment]
我也遇到同样问题，使用Yacd-meta，一切正常

**Comment by XiGou** [comment]
遇到一个类似问题，记录一下进展吧

我的metacubexd 部署在 NAS 上，有一个域名

当我用域名登录 UI，然后backend 用 ip 设置的时候，有跨站问题，会fetch失败

但是如果我将 backend 的格式写错了，写成 http:192.168.1.2:1234， 那么就会出现proxy页面无显示的情况

**Comment by hnzhaihui** [comment]
我也遇到了，关键是连配置页也进不去，一直转圈没反应，这越更新越多毛病啦
