### ISSUE TITLE
[ feature request ] 手动切换节点时自动打断相关连接

### ISSUE THREAD

**Issue by Brbrbr1995** [MetaCubeX/metacubexd#526]
类似 CFW 中的如下设置
![Screenshot 2023-12-25 170243](https://github.com/MetaCubeX/metacubexd/assets/150146865/59a5aba2-07e0-4f2a-bfc5-1c4aa5cec500)
没有此功能切换节时要到连接页手动筛选打断链接很不方便

**Comment by gg4924** [comment]
这个功能是有的，切换到代理，在右边的齿轮图标里，打开自动断开连接。
![Snipaste_2023-12-28_03-46-45](https://github.com/MetaCubeX/metacubexd/assets/21310130/74416487-ba21-4947-8cec-7707b890478a)
