### ISSUE TITLE
safari cannot scroll

### ISSUE THREAD

**Issue by levihuayuzhang** [MetaCubeX/metacubexd#527]
Cannot scroll page in Mac Safari (stable).

**Comment by levihuayuzhang** [comment]
Side scroll bar is ok (by using pointer to drag).
But the touch pad gesture seems not working.

**Comment by KingfuChan** [comment]
same issue. I managed to use arrow key to scroll, but in connection page it keeps flickering and hard to use

**Comment by freejool** [comment]
+1

**Comment by Duans** [comment]
+1，使用MenubarX完全无法滚动，我以为是人家软件有问题，给对方看了后说这个页面是定制的滚动条，不是使用的系统滚动条

**Comment by KingfuChan** [comment]
Seems to be fixed via #814. Waiting a bit before scrolling is now acceptable for me.
