### ISSUE TITLE
Rule规则界面看不到规则

### ISSUE THREAD

**Issue by anjue39** [MetaCubeX/metacubexd#573]
Rule规则界面看不到规则
![0215AC65-DB6A-4CA5-9554-E8DCEF4AE745](https://github.com/MetaCubeX/metacubexd/assets/98279987/3ccfd3fa-dced-47fa-822f-161ca7ee7e42)

**Comment by DEAN-Cherry** [comment]
我也碰到了这个问题, 本来我用 singbox 的,现在换回 mihomo 就好了,不知道为什么

**Comment by shiqianwei0508** [comment]
> 我也碰到了这个问题, 本来我用 singbox 的,现在换回 mihomo 就好了,不知道为什么

就是用的mihomo，也是规则界面卡死。

**Comment by VMatrices** [comment]
已经修复了
