### ISSUE TITLE
把设置保持到配置文件

### ISSUE THREAD

**Issue by llity** [MetaCubeX/metacubexd#596]
配色每次重新打开都变成了默认主题。

**Comment by curtisrecords** [comment]
网页上方设置图标 -> 修改浅色/深色主题偏好

**Comment by llity** [comment]
> 网页上方设置图标 -> 修改浅色/深色主题偏好

这个是可以修改，我意思加载上次选择的主题，不用每次打开需要设置

**Comment by llity** [comment]
大概知道了，这个跟随浏览器
