### ISSUE TITLE
docker img 无法下载

### ISSUE THREAD

**Issue by exp4sky** [MetaCubeX/metacubexd#631]
![image](https://github.com/MetaCubeX/metacubexd/assets/36186334/0b370333-ec3e-4517-b24f-b3b9d8f61ac0)

**Comment by fireflyddt** [comment]
+1

**Comment by kunish** [comment]
怎么复现的

**Comment by Fddh2012** [comment]
> 怎么复现的

不需要复现了，因为新编译的已经可以拉取到了。

**Comment by marcmk6** [comment]
> 怎么复现的

linux下pull image

**Comment by kunish** [comment]
把定期清理 docker 镜像的 action 先去掉了
