### ISSUE TITLE
手动点击策略组测速延时会假掉线

### ISSUE THREAD

**Issue by wangxi3709** [MetaCubeX/metacubexd#634]
手动点击策略组延时按钮，好多节点都会假死掉线，这个问题后面几个版本一直存在，最新的135还是同样的问题

**Comment by Xarth-Mai** [comment]
删掉ipv6测试试试 这个项目没什么人维护

**Comment by Xarth-Mai** [comment]
删掉ipv6测试url即可

**Comment by lazureice** [comment]
> 删掉ipv6测试url即可

请问在哪里删？我在设置里没找到。已经更新到了metacubexd-1.135.1，clash-meta-1.18。使用方式是external-ui.
另一个面板yacd倒是有一个设置测速url的地方。

**Comment by Xarth-Mai** [comment]
> > 删掉ipv6测试url即可
> 
> 请问在哪里删？我在设置里没找到。已经更新到了metacubexd-1.135.1，clash-meta-1.18。使用方式是external-ui. 另一个面板yacd倒是有一个设置测速url的地方。
![image](https://github.com/MetaCubeX/metacubexd/assets/72293030/6690e018-9285-45ed-a611-fbfa86238a2e)

**Comment by lazureice** [comment]
谢谢。原来在这。

**Comment by JZSTAR01** [comment]
我发现如果直接删掉刷新后会自动恢复然后检测仍然会假掉线，但是填入null即可
