### ISSUE TITLE
建议添加个 proxy-provider 下各节点的别名 tag，比如叫 alias_tag

### ISSUE THREAD

**Issue by fscarmen** [MetaCubeX/metacubexd#635]
有这样的使用场景，有多个 `proxy-provider` ，这样有就有多个不同协议集合的节点池，但现在各个节点名称是提供者起的，作为用户不能很好的管理。
希望达到的效果是节点池的节点1 ，能根据用户规则自定义命名，比如以 proxy 为前缀，节点1就叫 `proxy-1` ，同理节点2叫 `proxy-2`，但不是覆盖原来的节点 tag，而是添加一个字段比如叫 alias_tag，该自定义命名规则放在 `proxie-provider` 的字段下面，这个与 tag 在后面的分流规则都等效。
比如我有20个节点，能自定义名称为  proxy-1....proxy-20，用于后面的复杂分流场景。

**Comment by ObcbO** [comment]
问错地方了 这里是metacubex面板仓库
[MetaCubeX/mihomo](https://github.com/MetaCubeX/mihomo) 才是核心仓库

**Comment by fscarmen** [comment]
> 问错地方了 这里是metacubex面板仓库 [MetaCubeX/mihomo](https://github.com/MetaCubeX/mihomo) 才是核心仓库

抱歉，走错门了，谢谢提醒。
