### ISSUE TITLE
[Feature request]类似yacd的url参数读取功能，自动填写hostname,secret等

### ISSUE THREAD

**Issue by yuukh** [MetaCubeX/metacubexd#637]
希望可以实现当用带参数的url访问时，如 http://d.metacubex.one/ui/?hostname=http://*.*.*.*&port=9090&secret=xxxxxxx#/overview，
自动连接参数配置的服务端

**Comment by muink** [comment]
Query params support are also needed
Like as `https://d.metacubex.one/?host={host}&port={port}&secret={secret}`

**Comment by Howard20181** [comment]
XD v138 已经支持
`http://%host:%port/ui/#/setup?hostname=%host&port=%port&secret=%secret`

**Comment by muink** [comment]
d.metacubex.one 沒有部署 试试这个 metacubexd.pages.dev

**Comment by muink** [comment]
`http://metacubexd.pages.dev/#/setup?hostname=127.0.0.1&port=9090&secret=77484e5e-92ab-4cb5-bfa8-1785da4c1aa6`
@Howard20181 不知为何不再有效了

**Comment by JsonSong89** [comment]
好像是功能失效了
1.187.1都可以的,   升级到 1.235.0 (2025-12-25) 就不行了

**Comment by Howard20181** [comment]
> `http://metacubexd.pages.dev/#/setup?hostname=127.0.0.1&port=9090&secret=77484e5e-92ab-4cb5-bfa8-1785da4c1aa6` [@Howard20181](https://github.com/Howard20181) 不知为何不再有效了

`https://metacubexd.pages.dev/#/setup?hostname=127.0.0.1&port=9090&secret=your-secret&http=1`

for https:
`https://metacubexd.pages.dev/#/setup?hostname=127.0.0.1&port=9090&secret=your-secret&https=1`
