### ISSUE TITLE
1.136.0版本页面空白，无法显示任何信息

### ISSUE THREAD

**Issue by Bryan2333** [MetaCubeX/metacubexd#647]
RT，打开后除了上面那几个按钮，其余部分都是空白。

![图片](https://github.com/MetaCubeX/metacubexd/assets/31512600/58b11d0e-3494-4917-af6f-c224bd9f0d84)

开发者工具里面报错说 **You need to enable JavaScript to run this app.**

![屏幕截图_20240321_182730](https://github.com/MetaCubeX/metacubexd/assets/31512600/fee44647-d112-4b8b-b573-15ad3fcc27d1)

火狐浏览器和chromium-base的vivaldi浏览器都是这个情况。

**Comment by kunish** [comment]
清空一下缓存再试

**Comment by Bryan2333** [comment]
没用，清空缓存后还是一样。

控制台里面有个报错
![图片](https://github.com/MetaCubeX/metacubexd/assets/31512600/8efc380c-4a96-4316-8bc8-638023753c80)

**Comment by levihuayuzhang** [comment]
同，清空緩存後也無效。

**Comment by llity** [comment]
确实是空白

**Comment by hosxy** [comment]
我也是空白

**Comment by Victor2333** [comment]
+1

**Comment by clacknya** [comment]
确实。1.135.1就没有问题
