### ISSUE TITLE
IPv6测速导致部分节点无响应

### ISSUE THREAD

**Issue by SnowCore8** [MetaCubeX/metacubexd#650]
希望能增加IPv6测速的开关否则会导致节点测速的时候无法正确显示，
或者将IPv6和IPv4分开显示这样能一眼看出哪些支持IPv6

**Comment by forsignup** [comment]
删掉ipv6测速链接就不会测ipv6了

**Comment by SnowCore8** [comment]
> 删掉ipv6测速链接就不会测ipv6了

不，他还是会测，就很奇怪
