### ISSUE TITLE
分组规则带"/"节点会无法选择吗，比如:Github/Docker

### ISSUE THREAD

**Issue by lkxlzx** [MetaCubeX/metacubexd#684]
分组规则带/在中间，会无法选择分组内的节点，
比如这个的
- name: Github/Docker
  type: select
  proxies:
  - 自动选择
  - 故障转移
  - aws-首尔
  - aws-新加坡
  - desivps-圣何塞
  - cloudcone-洛杉矶
  - racknerd-洛杉矶
  - Juhost-香港
  - Juhost-日本
  - wikihost-日本
  - Cloudflare-vless
  disable-udp: false

**Comment by kunish** [comment]
大佬修了
