### ISSUE TITLE
external-ui-url这个配置起作用吗

### ISSUE THREAD

**Issue by lnc1995** [MetaCubeX/metacubexd#691]
文档中有这么个配置，但是没看到手动更新按钮或者自动更新的配置。
使用下来，比如external-ui配置中的目录没有文件的话，也不会触发自动下载？

**Comment by lnc1995** [comment]
看到了，代码已经实现了相关的功能。使用ROS系统的可以用这个命令触发下载：fetch url="http://IP:PORT/upgrade/ui"  http-method=post。希望后续更新能把自动下载实现

**Comment by lnc1995** [comment]
> 之前提过issue，这个功能需要手动触发，config页面添加个按钮就行，但是作者不愿意加，咱也不知道为啥

可能主程序里面代码还不完善，我测试下来，对文件夹的处理还比较初级没有完善，我在mihomo那边提了，不知道后续能不能改进一下

**Comment by kunish** [comment]
现在页面里有这个按钮了

https://github.com/MetaCubeX/metacubexd/pull/784

**Comment by lnc1995** [comment]
> 现在页面里有这个按钮了
> 
> #784

更新的逻辑是什么样的。原先是对external-ui这个配置的目录直接清空，即使这个目录下还有UI以外的文件甚至是系统目录也这么处理。希望把这个处理方式细化一下，比如服务器端多一个filelist文件，只删除external-ui配置的目录下命中filelist的文件，其他的不动。
