### ISSUE TITLE
手动切换选择一个后，同名的也被选中，是显示bug吗？

### ISSUE THREAD

**Issue by suikastar** [MetaCubeX/metacubexd#781]
选择第一个香港03，第二个香港03也被选中了
![QQ截图20240623131508](https://github.com/MetaCubeX/metacubexd/assets/53206264/6e06034a-8b3a-4369-901d-ce80d3f9e997)

**Comment by suikastar** [comment]
版本
![QQ截图20240623131705](https://github.com/MetaCubeX/metacubexd/assets/53206264/d60f6a9b-8f7d-484a-8c41-8bd91cd84e90)

**Comment by kunish** [comment]
这属于 api 设计缺陷

**Comment by suikastar** [comment]
> 这属于 api 设计缺陷

只影响显示吗？还是说同名节点会有一个始终选不上？

**Comment by kunish** [comment]
> > 这属于 api 设计缺陷
> 
> 
> 
> 只影响显示吗？还是说同名节点会有一个始终选不上？

具体什么表现不清楚，需要测试或者去查阅源码，目前可以自己加特定的前缀来解决

**Comment by suikastar** [comment]
> > > 这属于 api 设计缺陷
> > 
> > 
> > 只影响显示吗？还是说同名节点会有一个始终选不上？
> 
> 具体什么表现不清楚，需要测试或者去查阅源码，目前可以自己加特定的前缀来解决

好的，谢谢

**Comment by kunish** [comment]
https://wiki.metacubex.one/config/proxy-providers/#override
