### ISSUE TITLE
dns查询结果异常，没遵循配置文件内配置的hosts

### ISSUE THREAD

**Issue by suikastar** [MetaCubeX/metacubexd#785]
网页查询异常：
![QQ截图20240624212656](https://github.com/MetaCubeX/metacubexd/assets/53206264/f7cca0ee-aa8a-4419-b429-33fafacbf271)

本机查询正常：
```nslookup time.android.com
服务器:  UnKnown
Address:  10.0.1.1

名称:    time.android.com
Addresses:  ::ffff:203.107.6.88
          203.107.6.88
```

hosts配置：
![QQ截图20240624213511](https://github.com/MetaCubeX/metacubexd/assets/53206264/2dd82f92-21c2-4ece-b98a-f9a113b02509)

**Comment by kunish** [comment]
跟页面无关，可以去内核那边提
