### ISSUE TITLE
Mixed Content导致无法局域网访问

### ISSUE THREAD

**Issue by ZhaoGY-N** [MetaCubeX/metacubexd#812]
已经配置了 external-controller: 0.0.0.0:9090, 但是局域网访问的时候提示Failed to fetch，开发者工具console提示如下。
vendor-5507c805.js:28 Mixed Content: The page at 'https://d.metacubex.one/#/overview' was loaded over HTTPS, but requested an insecure resource 'http://192.168.0.9:9090/'. This request has been blocked; the content must be served over HTTPS.
有无解决办法？

**Comment by YetAnotherZephyruso** [comment]
在chrome://flags中进行如图的设置
![image](https://github.com/user-attachments/assets/8a70e95a-8f07-4d90-b8e8-b0fc52e3fff8)
并且现在更推荐使用https://metacubex.github.io/metacubexd

**Comment by HEUDavid** [comment]
> 在chrome://flags中进行如图的设置 ![image](https://private-user-images.githubusercontent.com/176294927/360305218-8a70e95a-8f07-4d90-b8e8-b0fc52e3fff8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3NTczMzcsIm5iZiI6MTcyNDc1NzAzNywicGF0aCI6Ii8xNzYyOTQ5MjcvMzYwMzA1MjE4LThhNzBlOTVhLThmMDctNGQ5MC1iOGU4LWIwZmM1MmUzZmZmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QxMTEwMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZGQxZTNmOTQyZTg0Y2Q2NGU3MDM0Nzg0MDcwNTM1YTAxNjA4MjllYzc3Mzk4OTUxZWQ2MTIzMTQ4Zjc1YmI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Iejqb0xwhBv08c_kaw_rokX0Wq6GK_7fMZOs3kqRG0g) 并且现在更推荐使用https://metacubex.github.io/metacubexd

-------------
如果是移动端局域网访问的话，基本很难设置允许不安全内容，iphone安全策略非常严格。
建议metacubex.github.io/metacubexd 同时允许http访问， 不要开启强制跳转https。

**Comment by YetAnotherZephyruso** [comment]
> 局域网访问

我理解现在openclash openwrt-mihomo sing-box等都有自带xd面板的功能，是什么需求需要不访问这些应用自带的面板而是选择公网的呢

**Comment by ZhaoGY-N** [comment]
目前使用的方法是直接将metacubexd放在ui文件夹中,通过9090/ui进行访问就可以了。之所以要选择这种方法通过局域网访问，是因为在一个无头的ubuntu服务器上使用，不是openwrt，如果有其他更好方案也请介绍一下，谢谢！

**Comment by HEUDavid** [comment]
> > 局域网访问
> 
> 我理解现在openclash openwrt-mihomo sing-box等都有自带xd面板的功能，是什么需求需要不访问这些应用自带的面板而是选择公网的呢

通过旁路由的方式，移动端设备通过局域网去访问web ui

**Comment by YetAnotherZephyruso** [comment]
> 不要开启强制跳转https。

就算不强制https，由于跨域的原因，应该还是无法在公网的网页上访问一个局域网的api

> 无头的ubuntu服务器

将xd面板也部署在这台ubuntu上，目前mihomo和sing-box都自带启动面板服务的功能，使用ubuntu上的面板访问ubuntu的api

**Comment by ZhaoGY-N** [comment]
> 将xd面板也部署在这台ubuntu上，目前mihomo (https://wiki.metacubex.one/config/general/#_7) 和sing-box (https://sing-box.sagernet.org/configuration/experimental/clash-api/#external_ui) 都自带启动面板服务的功能，使用ubuntu上的面板访问ubuntu的api

目前就是使用的这种方法,感谢回复!

**Comment by HEUDavid** [comment]
> > 不要开启强制跳转https。
> 
> 就算不强制https，由于跨域的原因，应该还是无法在公网的网页上访问一个局域网的api

不开启是可以的，我后面找到了yacd web ui 解决了，我在局域网下指定后端api是另一台局域网设备。
![207ac0a53ba2c717d5a9be4840f2a5d7](https://github.com/user-attachments/assets/dede7dc8-8a5d-426b-8fa6-42a379f63eb0)

**Comment by realpg** [comment]
> > 局域网访问
> 
> 我理解现在openclash openwrt-mihomo sing-box等都有自带xd面板的功能，是什么需求需要不访问这些应用自带的面板而是选择公网的呢

智能电视 残缺android系统
