### ISSUE TITLE
给“连接”和“日志”提点建议

### ISSUE THREAD

**Issue by DustinWin** [MetaCubeX/metacubexd#823]
1. 在“连接”栏目，在筛选后，“活动”会显示当前筛选出的连接数，且点击“×”按钮只断开筛选出的连接
<img src="https://github.com/MetaCubeX/metacubexd/assets/45238096/421344b9-24b0-4460-9bde-a8d453db8513" width="60%"/>

2. 在“日志”栏目，希望添加“暂停”功能，日志在自动刷新时可以手动暂停或继续

**Comment by fantasyroot** [comment]
同时希望“目标地址”能展示出实际请求的 ip，而不是代理节点的 ip，不然都全是代理节点 ip，用处不大。或者新增一个 “实际远程 ip” 的字段
