### ISSUE TITLE
[Bug] 隐藏不可用节点时会把没有延迟的策略组也隐藏

### ISSUE THREAD

**Issue by toddyoe** [MetaCubeX/metacubexd#874]
之前使用隐藏不可用节点功能时，策略组即使没有延迟数据也不会被隐藏， #868 这次修改后，如果粗略组没有延迟数据会被隐藏，切换时极不方便，希望能恢复之前的功能

**Comment by toddyoe** [comment]
@kunish 似乎没有编译/发版成功

**Comment by kunish** [comment]
https://github.com/MetaCubeX/metacubexd/pull/877

这次理论上可以了

**Comment by YetAnotherZephyruso** [comment]
> 策略组类型为“loadbalance”时，依旧会被隐藏 ![Screenshot_2024-07-30-19-37-00-762_mark via](https://private-user-images.githubusercontent.com/66180481/353441740-3e6f89e2-61a3-4451-b030-985a983b6c7f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNDAxNzcsIm5iZiI6MTcyMjMzOTg3NywicGF0aCI6Ii82NjE4MDQ4MS8zNTM0NDE3NDAtM2U2Zjg5ZTItNjFhMy00NDUxLWIwMzAtOTg1YTk4M2I2YzdmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDExNDQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyMTNlMTI4YTFiNGY1YzY4NDZkNjc1ZjM2NTcwNDBhYWU1YWY1M2E3ZGNmYTYxNDczYzM0NTkyYTUyNzkyNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qjov2aI1Jp5kneiG4kbvMKvPwUe7Q_w7qAYALIUBMlA) ![Screenshot_2024-07-30-19-37-07-421_mark via](https://private-user-images.githubusercontent.com/66180481/353441780-11719552-d0fe-45e3-9282-44bd92cfbe80.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNDAxNzcsIm5iZiI6MTcyMjMzOTg3NywicGF0aCI6Ii82NjE4MDQ4MS8zNTM0NDE3ODAtMTE3MTk1NTItZDBmZS00NWUzLTkyODItNDRiZDkyY2ZiZTgwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDExNDQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlZDY4YzEwOGY2ZjgyYWY2ZThlMWNlZmY4YzFhOTE1MTgzMDcxNDU2ZTlmZjY3NGU4ZmQ4ZDRmOWEwNDk2ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nq9ciIt-tOalE-nOf8ELIRaVNuSxaRtCQpup3buken0)

fixed in #881
