### ISSUE TITLE
不同的代理组中存在相同名字的节点时，两节点对应的是同一个组件

### ISSUE THREAD

**Issue by ayanami-desu** [MetaCubeX/metacubexd#893]
![image](https://github.com/user-attachments/assets/bcd89659-ae21-43b0-a5c3-ad39a280a034)
如图片所示，节点测速完成后，另一个节点也显示相同的延迟结果。

**Comment by YetAnotherZephyruso** [comment]
clash在设计之初没有使用uuid之类的唯一值作为节点的标识符，而是直接使用了节点名称作为标识符，请给节点赋予不同的名称用以区别
