### ISSUE TITLE
面板更新不是当前目录而是生成了新的XD目录

### ISSUE THREAD

**Issue by llity** [MetaCubeX/metacubexd#969]
![image](https://github.com/user-attachments/assets/a4bf501c-92b2-468a-bb7a-13ecef368537)

**Comment by YetAnotherZephyruso** [comment]
请找你对应的GUI软件反馈，这个不是面板本身负责的

**Comment by llity** [comment]
mihomo的docker版

**Comment by YetAnotherZephyruso** [comment]
请去mihomo反馈
