### ISSUE TITLE
若策略组所有节点都不支持ipv6，则不会进行ipv4的测速并显示延迟

### ISSUE THREAD

**Issue by gg4924** [MetaCubeX/metacubexd#991]
策略组内如果有至少一个支持ipv6的节点，对策略组测速会正常进行2个测速请求，一个ipv6一个ipv4。
![Snipaste_2024-09-11_09-33-36](https://github.com/user-attachments/assets/4cd064d8-c281-4fbd-b013-039dffe8d299)
但是如果策略组内的节点都不支持ipv6，对策略组测速就只有ipv6的请求，返回全部超时的信息，不会继续测ipv4链接并显示延迟。
![Snipaste_2024-09-11_09-36-33](https://github.com/user-attachments/assets/33fe92ef-7a04-488c-bd5c-37665485f77c)

**Comment by YetAnotherZephyruso** [comment]
请问是什么版本的xd和什么版本的后端
